# Generated by Django 5.2.6 on 2025-09-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('забронирован', 'забронирован'), ('подтвержден', 'подтвержден'), ('отменен', 'отменен')], default='забронирован', max_length=20),
        ),
    ]
